set -g default-terminal "screen-256color"
#unbind C-b
#set-option -g prefix M-Space
#bind Space send-prefix
set -g prefix C-Space
bind Space send-prefix
bind-key r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."
unbind '"'

unbind %
bind | split-window -h
bind - split-window -v

#set -g mouse on
# vim-like pane switching
bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R

