require("fernando.set")
require("fernando.lazy")
require("fernando.which_key")
require("fernando.colors")
require("fernando.nvim_tree")
require("fernando.telescope")
require("fernando.treesitter")
require("fernando.undotree")
